# Generated by Django 4.0.4 on 2022-08-18 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cake_Recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_recipe',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='template_recipe',
            name='recipe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='cake_Recipe.cake_recipe'),
        ),
        migrations.AddField(
            model_name='cake_recipe',
            name='coating',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='cake_Recipe.coating'),
        ),
        migrations.AddField(
            model_name='cake_recipe',
            name='flavour',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='cake_Recipe.flavor'),
        ),
        migrations.AddField(
            model_name='cake_recipe',
            name='frosting',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='cake_Recipe.frosting'),
        ),
    ]
