# Generated by Django 4.0.4 on 2022-08-22 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CakeLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.IntegerField()),
                ('layer_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DecorationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagetopdecoration_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.CreateModel(
            name='MsgColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_color_id', models.IntegerField()),
                ('color_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SpongFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor_id', models.IntegerField()),
                ('flavor_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Topping_Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fillingtopdecoration_id', models.IntegerField()),
                ('decoration_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('msg_on_cake', models.CharField(max_length=50)),
                ('special_instruction', models.CharField(max_length=500)),
                ('Sponge_Flavor', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customizeorder.spongflavor')),
                ('Top_Img_Decoration', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customizeorder.decorationimage')),
                ('Topping_Decoration', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customizeorder.topping_decoration')),
                ('layer_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customizeorder.cakelayer')),
                ('msg_color_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customizeorder.msgcolor')),
            ],
        ),
    ]
