# Generated by Django 4.0.4 on 2022-08-22 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customizeorder', '0002_decorationimage_name_alter_decorationimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeShapeAndLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.CharField(default=1, max_length=30)),
                ('cake_shape', models.CharField(default='Round Shape Cake', max_length=30)),
                ('layer_id', models.IntegerField()),
                ('layer_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FinalProductImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalProductImg', models.ImageField(upload_to='tool')),
                ('icing', models.IntegerField(default=0)),
                ('cake', models.IntegerField(default=0)),
                ('flavor', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Topping_Decoration',
            new_name='Icing',
        ),
        migrations.RenameField(
            model_name='customcake',
            old_name='Topping_Decoration',
            new_name='Icing',
        ),
        migrations.RenameField(
            model_name='customcake',
            old_name='msg_color_id',
            new_name='msg_color',
        ),
        migrations.RenameField(
            model_name='customcake',
            old_name='Sponge_Flavor',
            new_name='sponge_Flavor',
        ),
        migrations.RemoveField(
            model_name='customcake',
            name='layer_id',
        ),
        migrations.DeleteModel(
            name='CakeLayer',
        ),
        migrations.AddField(
            model_name='customcake',
            name='Cake_Shape_layers',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customizeorder.cakeshapeandlayers'),
        ),
        migrations.AddField(
            model_name='customcake',
            name='finalProduct',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customizeorder.finalproductimg'),
        ),
    ]
