# Generated by Django 4.0.4 on 2022-08-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizeorder', '0003_cakeshapeandlayers_finalproductimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgcolor',
            name='color_Code',
            field=models.CharField(default='#000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='customcake',
            name='msg_on_cake',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customcake',
            name='special_instruction',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
