# Generated by Django 4.0.4 on 2022-08-23 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customizeorder', '0004_msgcolor_color_code_alter_customcake_msg_on_cake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcake',
            name='customer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CustomCakeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_Status', models.CharField(choices=[('Order Pending', 'Order Pending'), ('Order Placed', 'Order Placed'), ('Under Package', 'Under Package'), ('On The way to deliver', 'On The way to deliver'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Order Pending', max_length=30)),
                ('order_Placment_Date', models.DateField(auto_now_add=True)),
                ('order_Placment_Time', models.TimeField(auto_now_add=True)),
                ('order_Delivery_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('order_Delivery_Time', models.CharField(default='2PM - 4PM', max_length=30)),
                ('delivery_Charges', models.FloatField(default='200', max_length=5)),
                ('address', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='order.address')),
                ('payment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.payment')),
            ],
        ),
        migrations.AddField(
            model_name='customcake',
            name='CustomCakeOrder',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customizeorder.customcakeorder'),
        ),
    ]
