# Generated by Django 4.0.4 on 2022-08-23 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customizeorder', '0005_customcake_customer_customcakeorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcake',
            name='CustomCakeOrder',
        ),
        migrations.RemoveField(
            model_name='customcakeorder',
            name='order_Status',
        ),
        migrations.AddField(
            model_name='customcake',
            name='order_Status',
            field=models.CharField(default='Order Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='CustomCake',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='customizeorder.customcake'),
        ),
    ]
