# Generated by Django 4.0.4 on 2022-08-18 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decoration', '0001_initial'),
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uploads_By',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cake_decoration',
            name='cake',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='base.cake'),
        ),
        migrations.AddField(
            model_name='cake_decoration',
            name='decortion_Element',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='decoration.decoration_element'),
        ),
    ]
