export {default as Toolbar} from './components/toolbar/Toolbar'; 
export {default as Header} from './components/header/Header'; 
export {default as Profile} from './pages/profile/Profile'; 
export {default as Customers} from './pages/customers/Customers'; 
export {default as CustomerEdit} from './pages/customers/CustomerEdit'; 
export {default as Products} from './pages/products/Products'; 
export {default as NewProduct} from './pages/products/NewProduct'; 
export {default as ProductEdit} from './pages/products/ProductEdit'; 
export {default as Feedbacks} from './pages/feedbacks/Feedbacks'; 
export {default as Question} from './pages/questions/Question' ; 
export {default as Orders} from './pages/orders/Orders';
export {default as OrderDetails} from './pages/orders/OrderDetails';
export {default as AdminDashboard} from './pages/dashboard/AdminDashboard'; 
export {default as Designtool} from './pages/designtool/Designtool'; 
export {default as CustomOrderDetails} from './pages/designtool/detaildOrder/CustomOrderDetails';
export {default as Notifications} from './pages/notifications/Notifications'; 
export {default as Sales} from './pages/sales/Sales';
export {default as Staff} from './pages/staff/Staff'; 
export {default as NewStaff} from './pages/staff/NewStaff'; 
export {default as AppLayout} from './pages/AppLayout/AppLayout';
export {default as UserLogin}  from "./auth/UserLogin";
export {default as Logout } from './auth/Logout';

