# Generated by Django 4.0.4 on 2022-08-18 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cake_Recipe', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_design',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='template_design',
            name='recipe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='base.design'),
        ),
        migrations.AddField(
            model_name='design_cakes',
            name='cake',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='base.cake'),
        ),
        migrations.AddField(
            model_name='design_cakes',
            name='design',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='base.design'),
        ),
        migrations.AddField(
            model_name='design',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='design',
            name='Design_Cakes',
            field=models.ManyToManyField(related_name='caks', through='base.Design_Cakes', to='base.cake'),
        ),
        migrations.AddField(
            model_name='cake',
            name='cake_recipe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='cake_Recipe.cake_recipe'),
        ),
    ]
