# Generated by Django 4.0.4 on 2022-08-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_Id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_Charges', models.FloatField()),
                ('total_Amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('catrgort_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Image_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='product')),
                ('image2', models.ImageField(upload_to='product')),
                ('image3', models.ImageField(upload_to='product')),
                ('image4', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_Id', models.AutoField(primary_key=True, serialize=False)),
                ('product_Name', models.CharField(max_length=50)),
                ('product_Description', models.TextField(max_length=700)),
                ('product_Price', models.FloatField()),
                ('product_Stock', models.PositiveIntegerField()),
                ('product_isSale', models.CharField(default='Yes', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imageGallery', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.image_gallery')),
                ('product_category', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product_In_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cart_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.cart')),
                ('product_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
